// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2992.Robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc2992.Robot.Robot;
import org.usfirst.frc2992.Robot.mhJoystick;

/**
 *
 */
public class DriveSticks extends Command {
	
	double counter;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public DriveSticks() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.mhRobotDrive);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    	counter = 0;
    	Robot.mhRobotDrive.allStop();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	mhJoystick leftJoy = Robot.oi.getLeftJoy();
    	mhJoystick rightJoy = Robot.oi.getRightJoy();
    	
    	double leftY = leftJoy.smoothGetY();
    	double rightY = rightJoy.smoothGetY();
    	
    	//counter to track if both joysticks are reading 0 values
    	
    	Robot.mhRobotDrive.tankDrive(leftY, rightY);
    	
    	if (leftY == 0 && rightY == 0){
    		counter++;
    	} else{
    		counter = 0;
    	}
    	
    	SmartDashboard.putNumber("Joystick counter", counter);
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.mhRobotDrive.allStop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.mhRobotDrive.allStop();
    }
}
