// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2992.Robot.commands;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc2992.Robot.Robot;
import org.usfirst.frc2992.Robot.subsystems.ShootPosition;

/**
 *
 */
public class ShootReady extends Command {
	
	Joystick ButtonBox;

    public ShootReady() {
    	ButtonBox = Robot.oi.getSwitchbox();
    	
        requires(Robot.shootReady);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	ButtonBox.setOutput(4, false);
    	ButtonBox.setOutput(5, false);
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	
    	//left light on button box
    	if(ShootPosition.ShootReadyLeft() == false){
    		ButtonBox.setOutput(4, true);
    	} else {
    		ButtonBox.setOutput(4, false);
    	}
    	
    	//right light on button box
    	if(ShootPosition.ShootReadyRight() == false){
    		ButtonBox.setOutput(5, true);
    	} else {
    		ButtonBox.setOutput(5, false);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	ButtonBox.setOutput(4, false);
    	ButtonBox.setOutput(5, false);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	ButtonBox.setOutput(4, false);
    	ButtonBox.setOutput(5, false);
    }
}
