// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2992.Robot.subsystems;

import org.usfirst.frc2992.Robot.Robot;
import org.usfirst.frc2992.Robot.RobotMap;
import org.usfirst.frc2992.Robot.commands.*;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class FeedInternal extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController feederwheel2 = RobotMap.feedInternal;
    private final DigitalInput feedersystemLimitswitch = RobotMap.feedLimit;
    
    // used to set the feed forward and reverse speeds.
    final double feedFspeed = .5;
    final double feedRspeed = -.5;
    
   
    
    public void feedIn(){
    	if(feedersystemLimitswitch.get() == false){
    		feederwheel2.set(feedFspeed);
    		SmartDashboard.putNumber("internal feed wheels", feederwheel2.get());
    	} else{
    		feederwheel2.set(0);
    	}
    }
    
    public void feedInFire(){
    	feederwheel2.set(feedFspeed);
    }
    
    public void feedOff(){
    	feederwheel2.set(0);
		SmartDashboard.putNumber("internal feed wheels", feederwheel2.get());
    }
    
    public void feedOut(){
    	feederwheel2.set(feedRspeed);
    	SmartDashboard.putNumber("internal feed wheels", feederwheel2.get());
    }
    
    public boolean limit(){
    return Robot.shooter.shootOn;
    }
    

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        setDefaultCommand(new FeedInternalOff());
    }
}

