// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2992.Robot;

import org.usfirst.frc2992.Robot.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);

    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.

    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:

    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());

    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());

    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	
	// 2 joysticks and 1 switchbox
	public mhJoystick leftJoy;
	public mhJoystick rightJoy;
	public Joystick switchbox;
	
	// joystick buttons
	public JoystickButton gearHigh;
	public JoystickButton gearLow;
	
	// switchbox buttons
	public JoystickButton shootHigh;
	public JoystickButton shootLow;
	public JoystickButton intakeInvert;
	public JoystickButton duckTailUpDown;
	public JoystickButton intakeOnOff;
	public JoystickButton flyWheelFastSlowOff;
	public JoystickButton intakeOut;
	public JoystickButton Auto1;
	public JoystickButton Auto2;
	public JoystickButton Auto3;
	
	// following button is regarding a possibility of being able to press a button to line yourself up and shoot for you.
	public JoystickButton smartShoot;
	
	

    public OI() {
    	// joysticks
        leftJoy = new mhJoystick(0);
        rightJoy = new mhJoystick(1);
        
        // switchbox
        switchbox = new Joystick(2);
        
        // Joystick button assignments, **need to verify**
        gearHigh = new JoystickButton(rightJoy, 1);
        gearLow = new JoystickButton(leftJoy, 1);
        
        //switchbox button assigments, **need to verify**
        
        Auto1 = new JoystickButton(switchbox, 14);
        Auto2 = new JoystickButton(switchbox, 15);
        Auto3 = new JoystickButton(switchbox, 16);
        shootHigh = new JoystickButton(switchbox, 5);
        shootLow = new JoystickButton(switchbox, 6);
        intakeInvert = new JoystickButton(switchbox, 4);
        duckTailUpDown = new JoystickButton(switchbox, 1);
        intakeOnOff = new JoystickButton(switchbox, 3);
        intakeOut = new JoystickButton(switchbox, 7);
        flyWheelFastSlowOff = new JoystickButton(switchbox, 2);
        
        shootHigh.whenPressed(new ShootHigh());
        shootLow.whenPressed(new ShootLow());
        
        intakeInvert.whenPressed(new FeedOut());
        
        duckTailUpDown.whenActive(new DuckTailUp());
        duckTailUpDown.whenInactive(new DuckTailDown());
        
        intakeOnOff.whenActive(new FeedIn());
        intakeOnOff.whenInactive(new FeedOff());
        if(intakeOnOff.get() == false){
        	intakeOut.whenActive(new FeedOut());
        }
        
    }
    
    public mhJoystick getLeftJoy(){
    	return leftJoy;
    }
    
    public mhJoystick getRightJoy(){
    	return rightJoy;
    }
    
    public Joystick getButtonBox(){
    	return switchbox;
    }
}

